// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAz4XiKdjxM6ytT-KYtTwXdLyi9fOy-Ml4",
    appId: "1:1051167403588:web:2e3a0716eed3c5f92b1611",
    messagingSenderId: "1051167403588",
    projectId: "devank-delivery-75fb2",
    authDomain: "devank-delivery-75fb2.firebaseapp.com",
    storageBucket: "devank-delivery-75fb2.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCXbiwyLaG6dofbepul5MsLgS0SQt9GLec",
    appId: "1:1051167403588:android:954adaa39d75f6f52b1611",
    messagingSenderId: "1051167403588",
    projectId: "devank-delivery-75fb2",
    storageBucket: "devank-delivery-75fb2.appspot.com",
    );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDVBipHCQ13w0GITxC9VWH1nHkQ6N_Ft3c",
    appId: "1:1051167403588:ios:abcd1234efgh5678ijkl",
    messagingSenderId: "1051167403588",
    projectId: "devank-delivery-75fb2",
    storageBucket: "devank-delivery-75fb2.appspot.com",
    androidClientId: '1051167403588-9ojh047hq84hchij8rpgr187er1ahtvn.apps.googleusercontent.com',
    iosClientId: '1051167403588-0hbpf13bgjv1v4jr5mp98751gmeb0ada.apps.googleusercontent.com',
    iosBundleId: 'com.devankdelivery',
  );
}
